# Generated by Django 4.1.5 on 2023-02-13 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingdetails",
            options={
                "verbose_name": "Shipping Detail",
                "verbose_name_plural": "Shipping Details",
            },
        ),
    ]
