# Generated by Django 4.1.5 on 2023-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_shippingdetails_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
